# Generated by Django 3.2 on 2022-11-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dexcription',
            new_name='description',
        ),
    ]
